project_id              = "emerald-trilogy-411720"
source_image_family     = "centos-stream-8"
disk_size               = 20
disk_type               = "pd-standard"
region                  = "us-central1"
zone                    = "us-central1-a"
image_name              = "csye6225-CentOS-VM{{timestamp}}"
image_description       = "Centos 8 VM"
image_family            = "centos-custom-image"
image_storage_locations = ["us"]
image_project_id        = "emerald-trilogy-411720"
machine_type            = "e2-medium"
ssh_username            = "packer"
network                 = "default" // will take default vpc