name: Authentication and Integration

# on:
#   pull_request:
#     types:
#       - closed
on:
  pull_request:
    branches: [ "main" ]

jobs:
  gcpAuth:
    name: gcpAuth
    # if: ${{ github.event.pull_request.merged == true }} 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      PORT: ${{ secrets.PORT }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      TOPIC:  ${{ secrets.TOPIC }}
      NODE_ENV: ${{ secrets.NODE_ENV }}


    steps:
      - uses: actions/checkout@v4

      - name: Setup Postgres
        run: |
          sudo apt update
          sudo apt install -y postgresql postgresql-contrib
          sudo systemctl start postgresql.service

          sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.DATABASE_NAME }};"
          sudo -u postgres psql -c "CREATE USER ${{ secrets.DATABASE_USER }} WITH PASSWORD '${{ secrets.DATABASE_PASSWORD }}';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${{ secrets.DATABASE_NAME }} TO ${{ secrets.DATABASE_USER }};"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm run build --if-present
      - run: npm install

      - name: Start the application
        run: |
          npm start &

      - name: Wait for the application to be ready
        run: |
          sleep 10
          until curl -s http://localhost:8080; do
            sleep 5
          done

      - run: npm test 
          
      - name: Delete any created node_modules
        run: rm -r node_modules

      - name: Zip the project
        run: |
          cd ../ && zip -r webapp.zip webapp && cd - && cp ../webapp.zip .

      - name: Check zip
        run: ls -l

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_AUTH_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Setup 'packer'
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: '1.10.1' # or 'latest'

      - name: Run 'packer init'
        id: init
        run: packer init gcpImageBuilder.pkr.hcl

      - name: Run 'packer Build'
        id: packer_build
        run: |
          echo "Running packer build"
          packer build gcpImageBuilder.pkr.hcl

      - name: Create new instance template version
        id: create_template
        run: |
            vm_instance_name=${{ secrets.NEW_IMAGE_NAMEINSTANCE_TEMPLATE_NAME }} 
            previous_instance_name="webapp-vmtemplate"
            region_url=$(gcloud compute instance-templates describe ${previous_instance_name} --region=${{ secrets.PROJECT_REGION }} --format="value(region)") #pass PROJECT_REGION through github secrets
            region=$(basename $region_url)
            machine_type="${{ secrets.MACHINE_TYPE }}"
            network=$(gcloud compute instance-templates describe ${previous_instance_name} --region=${{ secrets.PROJECT_REGION }} --format="value(properties.networkInterfaces.network)")
            subnetwork=$(gcloud compute instance-templates describe ${previous_instance_name} --region=${{ secrets.PROJECT_REGION }} --format="value(properties.networkInterfaces.subnetwork)")
            webapp_image_name=$(gcloud compute images list --filter="family=${{ secrets.CUSTOM_IMAGE_FAMILY }}" --sort-by=~creationTimestamp --format="value(name)" --limit=1) 
            webappimage_link=$(gcloud compute images describe ${webapp_image_name} --format="value(selfLink)")
            crypto_kms_key=$(gcloud compute instance-templates describe ${previous_instance_name} --region=${{ secrets.PROJECT_REGION }} --format="value(properties.disks.diskEncryptionKey.kmsKeyName)")
            disk_size=$(gcloud compute instance-templates describe ${previous_instance_name} --region=${{ secrets.PROJECT_REGION }} --format="value(properties.disks.initializeParams.diskSizeGb)")
            disk_type=$(gcloud compute instance-templates describe ${previous_instance_name} --region=${{ secrets.PROJECT_REGION }} --format="value(properties.disks.initializeParams.diskType)")
            labels=$(gcloud compute instance-templates describe ${previous_instance_name} --region=${{ secrets.PROJECT_REGION }} --format="value(properties.labels)")
            tags=$(gcloud compute instance-templates describe ${previous_instance_name} --region=${{ secrets.PROJECT_REGION }} --format="value(properties.tags.items)")
            metadata=$(gcloud compute instance-templates describe ${previous_instance_name} --region=${{ secrets.PROJECT_REGION }} --format="value(properties.metadata.items.value)")
            service_acc=$(gcloud compute instance-templates describe ${previous_instance_name} --region=${{ secrets.PROJECT_REGION }} --format="value(properties.serviceAccounts.email)")
            scopes=$(gcloud compute instance-templates describe ${previous_instance_name} --region=${{ secrets.PROJECT_REGION }} --format="value(properties.serviceAccounts.scopes)")
            scopes=$(echo "$scopes" | sed "s/\[\|\]//g") # Remove square brackets
            scopes=$(echo "$scopes" | sed "s/ *', *'/,/g") # Replace "', '" with comma
            scopes=$(echo "$scopes" | sed "s/^'//;s/'$//") # Remove single quotes at the start and end
            gcloud compute instance-templates create ${vm_instance_name} \
            --instance-template-region=${region} \
            --machine-type=${machine_type} \
            --region=${region} \
            --network=${network} \
            --subnet=${subnetwork} \
            --create-disk=image=${webappimage_link},boot=yes,auto-delete=yes,device-name=persistent-disk-0,size=${disk_size},type=${disk_type},kms-key=${crypto_kms_key} \
            --tags=${tags} \
            --metadata=startup-script="'${metadata}'" \
            --service-account=${service_acc} \
            --scopes=${scopes} \
            --reservation-affinity=any
            latetst_instance_template_self_link=$(gcloud compute instance-templates describe ${vm_instance_name} --region=${{ secrets.PROJECT_REGION }} --format="value(selfLink)")
            managed_instance_group="webappmig1"
            gcloud compute instance-groups managed rolling-action start-update  ${managed_instance_group} --version template=${latetst_instance_template_self_link} --region=${{ secrets.PROJECT_REGION }}
            gcloud compute instance-groups managed wait-until ${managed_instance_group} \
            --version-target-reached \
            --region=${{ secrets.PROJECT_REGION }}
